_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 3
                - 14
                - 17
                - 18
                - 19
                - 23
                - 55
            "4": 3.12.6
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
actual_train_images:
    value: 2042
batch_size:
    value: 128
dropout:
    value: 0.55
epochs:
    value: 1000
learning_rate:
    value: 0.005
optimizer:
    value: Adam
run_id:
    value: 6
train_percent:
    value: 0.2
train_percent_used:
    value: 0.2
